#!/bin/sh

OS=`uname -s`

if [ $OS = "Linux" ]; then
    echo "\033[44;37;1mRunning CellML...\033[0m"
fi

WMsg="CellML must first be built before being run."

if [ $OS = "Linux" ]; then
    if [ -f build/CellML ]; then
        build/CellML $*
    else
        echo $WMsg
    fi
else
    if [ -d build/CellML.app ]; then
        build/CellML.app/Contents/MacOS/CellML $*
    else
        echo $WMsg
    fi
fi

if [ $OS = "Linux" ]; then
    echo "\033[42;37;1mAll done!\033[0m"
fi
